# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Akhilesh

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'orc'
    packagesPath: 'C:\Users\akhileshk3\Documents\UiPath'
    folderName: 'akhilesh.kalgutkar@birlasoft.com''s workspace'